# Generated by Django 3.2 on 2023-07-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('accion_realizada', models.CharField(choices=[('encendido', 'Encendido'), ('apagado', 'Apagado'), ('ajuste_temperatura', 'Ajuste de temperatura')], max_length=50)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotica.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dispositivos', models.ManyToManyField(blank=True, related_name='habitaciones_rel', to='domotica.Dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_rel', to='domotica.habitacion'),
        ),
    ]
